package com.omneAgate.DTO;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

@Data
public class BeneficiaryActivationDto extends BaseDto implements Serializable {

    private static final long serialVersionUID = 1L;

    Long id;                    //Autogenerated unique identifier

    String oldRationNumber;

    char cardType;

    int cylinder;

    String mobileNumber;        // Registered mobile number of the beneficiary

    Date createdDate;

    long createdBy;

    long modifiedBy;

    Date modifiedDate;

    String ufc;

}
