package com.omneAgate.DTO;

import android.database.Cursor;
import android.util.Log;

import com.omneAgate.DTO.UserDto.BillItemProductDto;
import com.omneAgate.Util.Constants.FPSDBConstants;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.Data;

/**
 * This class is used to transfer Bill details
 *
 * @author user1
 */

@Data
public class BillDto extends BaseDto implements Serializable {

    long id;                        //AutoGenerated id

    long fpsId;                    //FPS id

    String billDate;                        //bill date

    long beneficiaryId;

    String createdby;                    //user who created the bill

    Double amount;                    //amount

    char mode;                        //Mode of identification. [R,Q,O]

    long bunkId;

    char channel;                    // Communication. Possible values [S ,G]

    Set<BillItemProductDto> billItemDto = new HashSet<>();

    String createdDate;

    long billRefId;

    long billLocalRefId;

    String billStatus;

    int billMonth;

    String ufc;

    String otpTime;

    long otpId;

    String transactionId;

    String rationCardNumber;

    String aRegisterNo;

//    List<BillItemDto> items;

    public BillDto() {

    }

    public BillDto(Cursor cur) {
       /* id = cur.getLong(cur
                .getColumnIndex(FPSDBConstants.KEY_BILL_));*/

            billMonth = cur.getInt(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_TIME_MONTH));
            String modes = cur.getString(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_MODE));
            mode = modes.charAt(0);

            ufc = cur.getString(cur.getColumnIndex(FPSDBConstants.KEY_BENEFICIARY_UFC));

            String channels = cur.getString(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_CHANNEL));
            channel = channels.charAt(0);

            createdby = cur.getString(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_CREATED_BY));


            billStatus = cur.getString(cur
                    .getColumnIndex("bill_status"));

            transactionId = cur.getString(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_TRANSACTION_ID));

            fpsId = cur.getLong(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_FPS_ID));

            billLocalRefId = cur.getLong(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_REF_ID));

            amount = cur.getDouble(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_AMOUNT));

            beneficiaryId = cur.getLong(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_BENEFICIARY));

            otpId = cur.getLong(cur.getColumnIndex("otpId"));

            otpTime = cur.getString(cur.getColumnIndex("otpTime"));


            billDate = cur.getString(cur
                    .getColumnIndex(FPSDBConstants.KEY_BILL_DATE));
        // billItems =

    }


}
