package com.omneAgate.DTO.EnumDTO;

/**
 * Created by user1 on 29/5/15.
 */
public enum TableNames {
    TABLE_CARDTYPE, TABLE_PRODUCT, TABLE_FPSMIGRATION,TABLE_SMSPROVIDER,TABLE_STOCKADJUSTMENT, TABLE_SPLRULES, TABLE_FPSSTORE, TABLE_PRODUCTGROUP, TABLE_PRICEOVERRIDE, TABLE_ENTITLEMENTMASTER, TABLE_PERSONBASEDRULE, TABLE_REGIONBASEDRULE, TABLE_BENEFICIARY, TABLE_BILL, TABLE_SERVICEPROVIDER, TABLE_USERDETAIL, TABLE_BUNKSTOCK, TABLE_FPSSTOCKINWARD,TABLE_ACTIVEFPS,TABLE_NEWACTIVEFPSBENEFICIARY,TABLE_GIVEITUPREQUEST
}
